#####################
## LIGHTS - presence
#####################
- id: few_lights_evening
  alias: Turn a few lights on when the sun gets dim
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 10.0
  condition:
    - condition: state
      entity_id: group.person_alle
      state: 'home'
    - condition: state
      entity_id: group.all_lights
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.light_down
#- id: more_lights
#  alias: Turn more lights on as the sun gets dimmer
#  trigger:
#    platform: numeric_state
#    entity_id: sun.sun
#    value_template: '{{ state.attributes.elevation }}'
#    below: 5.0
#  condition:
#    condition: state
#    entity_id: group.person_alle
#    state: 'home'
#  action:
#    service: scene.turn_on
#    entity_id: scene.light_up
- id: light_on_in_zone
  trigger:
  - platform: zone
    entity_id: device_tracker.9063f756
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: device_tracker.52005fa8f45ec44b
    zone: zone.home
    event: enter
  condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: 4.5
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.tobias_status
            state: 'Away'
          - condition: state
            entity_id: sensor.tobias_status
            state: 'Extended Away'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.kristine_status
            state: 'Away'
          - condition: state
            entity_id: sensor.kristine_status
            state: 'Extended Away'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_normal
- alias: night light time
  trigger:
    - platform: state
      entity_id: light.bad
      from: 'off'
      to: 'on'
  condition:
    condition: time
    after: '22:30:00'
    before: '05:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.night_light
